name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Mypy Check
        uses: jpetrucciani/mypy-check@0.761

      - name: Test with pytest
        run: |
          pytest

