name: Build
on: [push]
jobs:
  Run-Mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Mypy Check
        uses: jpetrucciani/mypy-check@0.761


